-- MySQL Script generated by MySQL Workbench
-- Mon Jul 22 02:31:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistemas_de_tickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemas_de_tickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemas_de_tickets` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistemas_de_tickets` ;

-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del cliente',
  `Nombre` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre del cliente',
  `Correo` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Correo electrónico del cliente',
  `Telefono` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Número de teléfono del cliente',
  `Direccion` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Dirección del cliente',
  `Pasaporte` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Número de pasaporte del cliente',
  `Estado` TINYINT(1) NULL DEFAULT NULL COMMENT 'Estado del cliente (activo/inactivo)',
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena información de los clientes';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`comentarios` (
  `idComentario` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del comentario',
  `Comentario` TEXT NULL DEFAULT NULL COMMENT 'Texto del comentario',
  `Fecha_de_creacion` DATE NULL DEFAULT NULL COMMENT 'Fecha de creación del comentario',
  `cliente` INT NULL DEFAULT NULL COMMENT 'Identificador del cliente que hizo el comentario',
  PRIMARY KEY (`idComentario`),
  INDEX `fk_comentarios_clientes_idx` (`cliente` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_clientes`
    FOREIGN KEY (`cliente`)
    REFERENCES `sistemas_de_tickets`.`clientes` (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena los comentarios de los clientes';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`departamentos` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del departamento',
  `nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre del departamento',
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena los diferentes departamentos';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`estado_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`estado_ticket` (
  `idEstado` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del estado del ticket',
  `descripcion` VARCHAR(50) NOT NULL COMMENT 'Descripción del estado del ticket',
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena los diferentes estados de los tickets';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`tipo_de_fallas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`tipo_de_fallas` (
  `idtipo_de_falla` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del tipo de falla',
  `nombre` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre del tipo de falla',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripción del tipo de falla',
  PRIMARY KEY (`idtipo_de_falla`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena los diferentes tipos de fallas';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`fallas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`fallas` (
  `idFalla` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único de la falla',
  `tipo_falla` INT NULL DEFAULT NULL COMMENT 'Identificador del tipo de falla',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripción de la falla',
  `estado` TINYINT(1) NULL DEFAULT NULL COMMENT 'Estado de la falla (activa/inactiva)',
  PRIMARY KEY (`idFalla`),
  INDEX `fk_fallas_tipo_de_fallas_idx` (`tipo_falla` ASC) VISIBLE,
  CONSTRAINT `fk_fallas_tipo_de_fallas`
    FOREIGN KEY (`tipo_falla`)
    REFERENCES `sistemas_de_tickets`.`tipo_de_fallas` (`idtipo_de_falla`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena las fallas reportadas';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`permisos` (
  `idPermiso` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del permiso',
  `Permiso` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Descripción del permiso',
  `Estado` TINYINT(1) NULL DEFAULT NULL COMMENT 'Estado del permiso (activo/inactivo)',
  PRIMARY KEY (`idPermiso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena los diferentes permisos';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`tipo_de_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`tipo_de_usuarios` (
  `idTipo_de_usuario` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del tipo de usuario',
  `Tipo_de_usuario` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Descripción del tipo de usuario',
  `Estado` TINYINT(1) NULL DEFAULT NULL COMMENT 'Estado del tipo de usuario (activo/inactivo)',
  PRIMARY KEY (`idTipo_de_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena los diferentes tipos de usuarios';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`permisos_de_tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`permisos_de_tipo_usuarios` (
  `idpermiso_de_tipo_usuario` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único de la asignación de permiso al tipo de usuario',
  `idTipo_de_usuario` INT NOT NULL COMMENT 'Identificador del tipo de usuario. Similar a idRole en roles_permisos.',
  `idPermiso` INT NOT NULL COMMENT 'Identificador del permiso. Común con roles_permisos.',
  PRIMARY KEY (`idpermiso_de_tipo_usuario`),
  INDEX `idTipo_de_usuario` (`idTipo_de_usuario` ASC) VISIBLE,
  INDEX `idPermiso` (`idPermiso` ASC) VISIBLE,
  CONSTRAINT `permisos_de_tipo_usuarios_ibfk_1`
    FOREIGN KEY (`idTipo_de_usuario`)
    REFERENCES `sistemas_de_tickets`.`tipo_de_usuarios` (`idTipo_de_usuario`),
  CONSTRAINT `permisos_de_tipo_usuarios_ibfk_2`
    FOREIGN KEY (`idPermiso`)
    REFERENCES `sistemas_de_tickets`.`permisos` (`idPermiso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que asigna permisos a los diferentes tipos de usuarios. Similar a roles_permisos, pero enfocado en tipos de usuarios.';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`personal` (
  `idPersonal` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del personal',
  `nombre` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre del personal',
  `apellido` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Apellido del personal',
  `fecha_nacimiento` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Fecha de nacimiento del personal',
  `correo_electronico` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Correo electrónico del personal',
  `telefono` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Número de teléfono del personal',
  `direccion` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Dirección del personal',
  `genero` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Género del personal',
  `DUI` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Documento Único de Identidad del personal',
  `Estado` TINYINT(1) NULL DEFAULT NULL COMMENT 'Estado del personal (activo/inactivo)',
  `idDepartamento` INT NULL DEFAULT NULL COMMENT 'Identificador del departamento al que pertenece el personal',
  PRIMARY KEY (`idPersonal`),
  INDEX `fk_personal_departamento_idx` (`idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_personal_departamento`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `sistemas_de_tickets`.`departamentos` (`idDepartamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena la información del personal';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`roles` (
  `idRole` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del rol',
  `roleName` VARCHAR(50) NOT NULL COMMENT 'Nombre del rol',
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena los diferentes roles';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`personal_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`personal_roles` (
  `idPersonal` INT NOT NULL COMMENT 'Identificador del personal',
  `idRole` INT NOT NULL COMMENT 'Identificador del rol',
  INDEX `idPersonal` (`idPersonal` ASC) VISIBLE,
  INDEX `idRole` (`idRole` ASC) VISIBLE,
  CONSTRAINT `personal_roles_ibfk_1`
    FOREIGN KEY (`idPersonal`)
    REFERENCES `sistemas_de_tickets`.`personal` (`idPersonal`),
  CONSTRAINT `personal_roles_ibfk_2`
    FOREIGN KEY (`idRole`)
    REFERENCES `sistemas_de_tickets`.`roles` (`idRole`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que asigna roles al personal';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`roles_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`roles_permisos` (
  `idRole` INT NOT NULL COMMENT 'Identificador del rol. Similar a idTipo_de_usuario en permisos_de_tipo_usuarios.',
  `idPermiso` INT NOT NULL COMMENT 'Identificador del permiso. Común con permisos_de_tipo_usuarios.',
  INDEX `idRole` (`idRole` ASC) VISIBLE,
  INDEX `idPermiso` (`idPermiso` ASC) VISIBLE,
  CONSTRAINT `roles_permisos_ibfk_1`
    FOREIGN KEY (`idRole`)
    REFERENCES `sistemas_de_tickets`.`roles` (`idRole`),
  CONSTRAINT `roles_permisos_ibfk_2`
    FOREIGN KEY (`idPermiso`)
    REFERENCES `sistemas_de_tickets`.`permisos` (`idPermiso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que asigna permisos a los roles. Similar a permisos_de_tipo_usuarios, pero enfocado en roles.';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del usuario',
  `Tipo_de_usuario` INT NULL DEFAULT NULL COMMENT 'Identificador del tipo de usuario',
  `Usuario` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre de usuario',
  `Contrasena` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Contraseña del usuario',
  `Estado` TINYINT(1) NULL DEFAULT NULL COMMENT 'Estado del usuario (activo/inactivo)',
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuarios_tipo_de_usuario_idx` (`Tipo_de_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_de_usuario`
    FOREIGN KEY (`Tipo_de_usuario`)
    REFERENCES `sistemas_de_tickets`.`tipo_de_usuarios` (`idTipo_de_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena la información de los usuarios';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`tipo_de_falla_hadware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`tipo_de_falla_hadware` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del tipo de falla de hardware',
  `nombre` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre del tipo de falla de hardware',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripción del tipo de falla de hardware',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena los diferentes tipos de fallas de hardware';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`tipo_de_falla_software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`tipo_de_falla_software` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del tipo de falla de software',
  `nombre` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre del tipo de falla de software',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripción del tipo de falla de software',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena los diferentes tipos de fallas de software';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`tickets` (
  `idTicket` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del ticket',
  `Fecha_de_resevimiento_del_equipo` DATE NULL DEFAULT NULL COMMENT 'Fecha de recepción del equipo',
  `Fecha_de_creacion_del_ticket` DATE NULL DEFAULT NULL COMMENT 'Fecha de creación del ticket',
  `Numero_de_ticket` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Número de ticket',
  `Descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripción del ticket',
  `Fecha_de_actualizacion_de_tickets` DATE NULL DEFAULT NULL COMMENT 'Fecha de actualización del ticket',
  `Fecha_de_solucion` DATE NULL DEFAULT NULL COMMENT 'Fecha de solución del ticket',
  `Entrega_del_equipo` DATE NULL DEFAULT NULL COMMENT 'Fecha de entrega del equipo',
  `Comentario` INT NULL DEFAULT NULL COMMENT 'Identificador del comentario relacionado con el ticket',
  `Falla` INT NOT NULL COMMENT 'Identificador de la falla relacionada con el ticket',
  `tipo_de_falla_hadware` INT NULL DEFAULT NULL COMMENT 'Identificador del tipo de falla de hardware',
  `tipo_de_falla_software` INT NULL DEFAULT NULL COMMENT 'Identificador del tipo de falla de software',
  `usuario` INT NOT NULL COMMENT 'Identificador del usuario que creó el ticket',
  `idEstado` INT NOT NULL COMMENT 'Identificador del estado del ticket',
  `idCliente` INT NULL DEFAULT NULL COMMENT 'Identificador del cliente relacionado con el ticket',
  `creado_por` INT NULL DEFAULT NULL COMMENT 'Identificador del usuario que creó el ticket',
  `manejado_por` INT NULL DEFAULT NULL COMMENT 'Identificador del usuario que manejó el ticket',
  `cerrado_por` INT NULL DEFAULT NULL COMMENT 'Identificador del usuario que cerró el ticket',
  PRIMARY KEY (`idTicket`),
  INDEX `tickets_cometario_idx` (`Comentario` ASC) VISIBLE,
  INDEX `fk_ticket_fallas_idx` (`Falla` ASC) VISIBLE,
  INDEX `fk_ticket_usario_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_ticket_tipo_de_falla_software_idx` (`tipo_de_falla_software` ASC) VISIBLE,
  INDEX `fk_ticket_tipo_de_falla_hadware_idx` (`tipo_de_falla_hadware` ASC) VISIBLE,
  INDEX `fk_estado_ticket` (`idEstado` ASC) VISIBLE,
  INDEX `fk_ticket_cliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_ticket_creado_por_idx` (`creado_por` ASC) VISIBLE,
  INDEX `fk_ticket_manejado_por_idx` (`manejado_por` ASC) VISIBLE,
  INDEX `fk_ticket_cerrado_por_idx` (`cerrado_por` ASC) VISIBLE,
  CONSTRAINT `fk_estado_ticket`
    FOREIGN KEY (`idEstado`)
    REFERENCES `sistemas_de_tickets`.`estado_ticket` (`idEstado`),
  CONSTRAINT `fk_ticket_cerrado_por`
    FOREIGN KEY (`cerrado_por`)
    REFERENCES `sistemas_de_tickets`.`usuarios` (`idUsuario`),
  CONSTRAINT `fk_ticket_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `sistemas_de_tickets`.`clientes` (`idCliente`),
  CONSTRAINT `fk_ticket_comentario`
    FOREIGN KEY (`Comentario`)
    REFERENCES `sistemas_de_tickets`.`comentarios` (`idComentario`),
  CONSTRAINT `fk_ticket_creado_por`
    FOREIGN KEY (`creado_por`)
    REFERENCES `sistemas_de_tickets`.`usuarios` (`idUsuario`),
  CONSTRAINT `fk_ticket_fallas`
    FOREIGN KEY (`Falla`)
    REFERENCES `sistemas_de_tickets`.`fallas` (`idFalla`),
  CONSTRAINT `fk_ticket_manejado_por`
    FOREIGN KEY (`manejado_por`)
    REFERENCES `sistemas_de_tickets`.`usuarios` (`idUsuario`),
  CONSTRAINT `fk_ticket_tipo_de_falla_hadware`
    FOREIGN KEY (`tipo_de_falla_hadware`)
    REFERENCES `sistemas_de_tickets`.`tipo_de_falla_hadware` (`id`),
  CONSTRAINT `fk_ticket_tipo_de_falla_software`
    FOREIGN KEY (`tipo_de_falla_software`)
    REFERENCES `sistemas_de_tickets`.`tipo_de_falla_software` (`id`),
  CONSTRAINT `fk_ticket_usario`
    FOREIGN KEY (`usuario`)
    REFERENCES `sistemas_de_tickets`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla que almacena la información de los tickets';


-- -----------------------------------------------------
-- Table `sistemas_de_tickets`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemas_de_tickets`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
